baseURL = "/"
locale = "en-us"
title = "Stars"
defaultContentLanguage = "en"

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"

[params]
  BookSection = "pages"
  BookSearch = true
  BookToC = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
